version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cybersecurity_portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cybersecurity_portfolio
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - portfolio_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cybersecurity_portfolio_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cybersecurity.com
      PGADMIN_DEFAULT_PASSWORD: Admin123!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - portfolio_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  portfolio_network:
    driver: bridge
